### ISSUE TITLE
Update source to the latest version of Sirius 4.4.29+

### ISSUE THREAD

**Issue by anupriyatripathi** [biocore/q2-qemistree#136]
Requires changes to command line calls in`_fingerprint.py`. Will likely speed up the first three steps: `compute-fragmentation-trees`, `rerank-molecular-formulas`, `predict-fingerprints`; new version also handles some common fingerprinting errors.

Sirius: https://bio.informatik.uni-jena.de/software/sirius/

**Comment by helenamrusso** [comment]
Hi Priya, 

Since we got to the [end of life](https://bio.informatik.uni-jena.de/2021/04/sirius-4-0-1-end-of-life/) of Sirius 4.0.1, I have been working together with @wilhan-nunes to try to make the q2-qemistree plugin work with the latest Sirius version (Sirius 4.8.2). We made some progress and got it to work properly. I'm uploading here the files that we altered: **_plugin_setup.txt** ; **_fingerprint.txt** ; **_process_fingerprint.txt**. I'm uploading them as txt since I can't upload .py files.

It is _definitely not perfect_, for some reason we were not able to change the descriptions (when we change the descriptions, we get some errors). But anyway, we thought it could be useful/helpful.

I tested one of my dataset that I had the outputs and trees for the sirius 4.0.1. The running time decreased significantly in the compute-fragmentation-trees step (from ~10 h to ~6 h), and even more in the rerank-molecular-formulas (from ~7 h to 17 min). Something I noticed on my exported .mgf files for Sirius (from MZmine2), is that not all MS1 have MS2 (I also observe that for the sirius.mgf files from one of the examples used in the paper [MSV000085226](https://massive.ucsd.edu/ProteoSAFe/dataset.jsp?task=c1ffe293c433446fa2222d088abc9b1f)). In the previous version, it spent a lot of time calculating the fragmentation trees even for the ones that had just MS1. This new version already filters and considers only the ones with MS2.

Finally, we also want to emphasize that we tested it for the OSx version ([sirius-4.8.2-osx64-headless.zip](https://bio.informatik.uni-jena.de/repository/dist-release-local/de/unijena/bioinf/ms/sirius/4.8.2/)).
We would be happy if you could comment and/or make suggestions when possible! We sincerely hope it helps. Let us know if you have any questions.

Best,
Helena and Will


[plugin_setup.txt](https://github.com/biocore/q2-qemistree/files/6640869/plugin_setup.txt)
[_process_fingerprint.txt](https://github.com/biocore/q2-qemistree/files/6640870/_process_fingerprint.txt)
[_fingerprints.txt](https://github.com/biocore/q2-qemistree/files/6640871/_fingerprints.txt)

**Comment by anupriyatripathi** [comment]
Hi Helena and Will,

Thanks so much for working on this very important module for Qemistree. We
really appreciate your contribution!
Could you please submit your code modifications as a pull request
<https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests>
to
the q2-qemistree repository <https://github.com/biocore/q2-qemistree>?
We'll be sure to review it rapidly and make it available to other users!

Thanks again for this important contribution!

Best regards, Priya

Anupriya Tripathi, PhD
